"""Add jobs and applications tables

Revision ID: 4cee626c18d1
Revises: b581bd74a949
Create Date: 2025-08-02 18:16:44.759404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cee626c18d1'
down_revision: Union[str, Sequence[str], None] = 'b581bd74a949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.Enum('full-time', 'part-time', 'contract', 'internship', name='job_type'), nullable=True),
    sa.Column('experience_level', sa.Enum('entry-level', 'mid-level', 'senior-level', 'executive', name='experience_level'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'archived', name='job_status'), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('resume_url', sa.String(length=255), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'shortlisted', 'rejected', name='application_status'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('jobs')
    # ### end Alembic commands ###
